package EchoApp;


/**
* EchoApp/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* Sunday, December 13, 2015 11:00:09 PM JST
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
