package EchoApp;

/**
* EchoApp/EchoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* Tuesday, December 15, 2015 12:24:17 AM JST
*/

public final class EchoHolder implements org.omg.CORBA.portable.Streamable
{
  public EchoApp.Echo value = null;

  public EchoHolder ()
  {
  }

  public EchoHolder (EchoApp.Echo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EchoApp.EchoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EchoApp.EchoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EchoApp.EchoHelper.type ();
  }

}
