package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* Tuesday, December 15, 2015 12:24:17 AM JST
*/

public interface EchoOperations 
{
  void echoString (String input);
} // interface EchoOperations
