package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* Sunday, December 13, 2015 11:00:09 PM JST
*/

public interface EchoOperations 
{
  void echoString (String input);
} // interface EchoOperations
